import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillGithub, AiFillTwitterCircle } from 'react-icons/ai';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hamza Berqia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
        <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-xl font-montserrat">HamzaCodes</h1>  
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
            </li>
            <li>
              <a className= "bg-cyan-400 text-white px-4 py-2 rounded-md ml-8" href='/docs/HamzaBerqiaCV'>Resume</a>
            </li>
          </ul>
        </nav>
        <div className="text-canter p-10">
          <h2 className="text-5xl py-2 text-cyan-400 font-medium">Hamza Berqia</h2>
          <h3 className="text-2xl py-2">Developer and UX Designer.</h3>
          <p>
            Freelancer providing services for frontend and UX design. 
          </p>
        </div>
        <div>
          <AiFillLinkedin />
          <AiFillGithub />
          <AiFillTwitterCircle />
        </div>
        
        </section>
      </main>
    </div>
  );
}
