import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import { useState } from 'react';
import Typed from 'react-typed';
import Link from 'next/link';

export default function Resume() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="bg-white px-10 dark:bg-gray-900 ">
        <section className="min-h-screen">
          <nav className="py-10 mb-2 flex justify-between">
            <h1 className="text-2xl font-montserrat text-gray-800 dark:text-white">Hamza Berqia - Trowbridge - 07715643578 - hamzaberqia<span className='text-cyan-400'>@</span>hotmail.com</h1>
            <ul className="flex items-left">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl text-gray-800 dark:text-white" />
              </li>
            </ul>
          </nav>
          <div className="text-left p-10">

            <h4 className='text-xl py-2 text-gray-800 dark:text-white'><b>Introductory Profile</b></h4>
            <p className='text-md py-1 leading-8 text-gray-800 dark:text-white'>Ambitious, dynamic, and adept Computer Science Graduate with a passion
              for new and emerging technologies, coupled with a love of web and
              application development. Built awareness encompassing web technologies
              and development during recent studies. Academic achievements are
              underpinned by a mix of professional experience in multifaceted and
              deadline-driven settings necessitating self-motivation and a positive
              response to pressure. Relishes challenges and is quick and willing to learn
              and apply new processes and procedures. Strong cultural awareness, global
              mind-set, and bilingual skills (English / Arabic) gained via a love of
              international travel.</p>
              <h6 className='text-right p-10 text-xl py-2 text-gray-800 dark:text-white'><b>Skills</b></h6>
              <h5 className='text-xl py-2 text-gray-800 dark:text-white'><b>Education<span className='text-cyan-400'> & </span></b><b>Qualifications</b></h5>
              <h5 className='text-xl py-2 text-gray-800 dark:text-white'><b>Professional Experience<span className='text-cyan-400'> & </span></b><b>Achievements</b></h5>
              <h5 className='text-xl py-2 text-gray-800 dark:text-white'><b>Personal Highlights</b></h5>
              <h5 className='text-xl py-2 text-gray-800 dark:text-white'><b>Other</b></h5>
              

          </div>
        </section>
      </main>

    </div>


  )
}
